@startuml

state Registry

note "FROM EXISTING_IMAGE\nCOPY FILES\nRUN\nCMD" as N1


state de 

state Dockerfile

state "docker engine" as de  {
  state RunningContainer
  state StopedContainer

}

state image

image --> RunningContainer: docker run
note on link 
--detach
--name=[container_name]
--env="MYSQL_ROOT_PASSWORD=[my_password]"
--publish 6603:3306
--volume=/FOLDER
end note

image --> StopedContainer: docker create

RunningContainer -Right-> StopedContainer : docker stop CONTAINER_NAME
StopedContainer -Left-> RunningContainer :docker start CONTAINER_NAME


Registry -> image: docker pull IMAGE_NAME
image -> Registry: docker push

Dockerfile --> image: docker build
@enduml
